version: "3.9"

services:
  stick-studio-backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - .env
    environment:
      PORT: "${PORT:-3001}"
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev"

    networks:
          - default
          - hong_service

networks:
  hong_service:
    external: true